### ISSUE TITLE
The link 'API documentation' does not work 

### ISSUE THREAD

**Issue by atoyalvin** [IBM-Bluemix-Docs/vpc#75]
Go to https://cloud.ibm.com/docs/infrastructure/vpc?topic=vpc-rias-error-messages#token_invalid
Click on link [API documentation](https://cloud.ibm.com/apidocs/rias)
![image](https://user-images.githubusercontent.com/17350842/55464043-d8f51180-562c-11e9-8692-f2e0b0e1a86c.png)

Actual Results:
The page isn't available.
![image](https://user-images.githubusercontent.com/17350842/55463749-43598200-562c-11e9-9925-6dfb3ca554c8.png)

Expect Results:
The page could work fine.

@neal-timpe  @llundquist 
Please help to investigate it.

**Comment by ibm-cos-help** [comment]
VPC is a whitelisted product and the API docs are tied to that whitelist. You need to be logged in and in the context of a whitelisted account to see the docs. In the top right drop down menu, choose a whitelisted account and refresh the page.

**Comment by atoyalvin** [comment]
Will try it.
Thanks for your info.
